import {curriculum,songs} from '../data/mock-kzsl-dataset.js';
import {GestureRecognizer,MockModelAdapter,MotionBuffer,TemporalModelAdapter} from './recognizer.js';
import {account,mountAccount} from './account.js';

const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const LAST_LESSON='qazaqsign_last_lesson_v1';
const state={level:curriculum[0],lesson:curriculum[0].lessons[0],camera:null,motion:new MotionBuffer(48),score:0,song:songs[0],songSection:0};
let model=new MockModelAdapter();
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800);}
function show(view){if(view!=='lesson')releaseCamera();$$('.view').forEach(el=>el.classList.toggle('active',el.id===`${view}View`));$$('[data-nav]').forEach(el=>el.classList.toggle('active',el.dataset.nav===view));window.scrollTo({top:0,behavior:'smooth'});}
function locateLesson(id){for(const level of curriculum){const lesson=level.lessons.find(item=>item.id===id);if(lesson)return {level,lesson};}return null;}
function savePosition(){const position={levelId:state.level.id,lessonId:state.lesson.id,updatedAt:Date.now()};localStorage.setItem(LAST_LESSON,JSON.stringify(position));if(curriculum.includes(state.level))account.saveProgress({lessonId:position.lessonId,levelId:position.levelId,accuracy:0,completed:false}).catch(()=>{});}
async function resumeLearning(){let saved;try{saved=JSON.parse(localStorage.getItem(LAST_LESSON));}catch{}if(account.current()){try{const remote=(await account.getProgress()).find(item=>locateLesson(item.lessonId));if(remote&&(!saved||new Date(remote.updatedAt).getTime()>saved.updatedAt))saved=remote;}catch{}}const location=saved&&locateLesson(saved.lessonId);if(location){state.level=location.level;state.lesson=location.lesson;}else{state.level=curriculum[0];state.lesson=curriculum[0].lessons[0];}renderLesson();show('lesson');}
function renderLevels(){$('#levelGrid').innerHTML=curriculum.map(level=>`<article class="level-card" data-level="${level.id}"><span class="level-number">${level.number}</span><div class="level-art" style="--tone:${level.tone}">${level.icon}</div><h3>${level.title}</h3><p>${level.description}</p><footer><span>${level.lessons.length} тақырып</span><b>${level.progress}% →</b></footer></article>`).join('');$$('.level-card').forEach(card=>card.onclick=()=>openLevel(card.dataset.level));}
function openLevel(id){state.level=curriculum.find(level=>level.id===id);state.lesson=state.level.lessons[0];savePosition();renderLesson();show('lesson');}
function setLesson(lessonId){state.lesson=state.level.lessons.find(item=>item.id===lessonId);savePosition();renderLesson();}
function renderLesson(){const {level,lesson}=state;$('#lessonEyebrow').textContent=`${level.number} / ${level.title.toUpperCase()}`;$('#lessonTitle').textContent=level.title;$('#lessonDescription').textContent=level.description;$('#sublessonList').innerHTML=level.lessons.map((item,index)=>`<button class="sublesson ${item.id===lesson.id?'active':''}" data-lesson="${item.id}"><span>0${index+1}</span><b>${item.title}</b></button>`).join('');$$('.sublesson').forEach(button=>button.onclick=()=>setLesson(button.dataset.lesson));$('#gestureEmoji').textContent=lesson.gesture;$('#exercisePrompt').textContent=lesson.prompt;$('#exerciseHint').textContent=lesson.hint;const index=level.lessons.indexOf(lesson);$('#exerciseStep').textContent=`${index+1} / ${level.lessons.length} жаттығу`;$('#stageProgress').style.width=`${((index+1)/level.lessons.length)*100}%`;$('#feedbackText').textContent='Камераны қосып, қимылды қайталаңыз';$('#accuracyValue').textContent='—';}
function updateCameraStatus(status){const box=$('.camera-status'),empty=$('#cameraEmpty');if(status==='live'){box.classList.add('live');$('#cameraStatus').textContent='Бет, бас және қимыл бақылануда';empty.classList.add('hidden');$('#startPractice').textContent='Камера қосулы';$('#checkGesture').disabled=false;}else{box.classList.remove('live');$('#cameraStatus').textContent='Камераны қосыңыз';empty.classList.remove('hidden');}}
function releaseCamera(){if(!state.camera)return;state.camera.stop();state.camera=null;state.motion.clear();updateCameraStatus('idle');}
async function startCamera(){if(state.camera)return;try{state.motion.clear();state.camera=new GestureRecognizer({video:$('#inputVideo'),canvas:$('#handCanvas'),onStatus:updateCameraStatus,onFrame:results=>state.motion.add(results)});await state.camera.start();toast('Камера қосылды — бетті, басты және қимылды кадрда ұстаңыз.');}catch(error){toast(error.message);state.camera=null;}}
function scoreGesture(){const answer=model.predict(state.motion.latest(),state.lesson);state.score=answer.score;$('#accuracyValue').textContent=answer.score?`${answer.score}%`:'—';$('#feedbackText').textContent=answer.message;if(answer.score>=86){toast('Жаттығу сәтті аяқталды!');const current=Number($('#overallAccuracy').textContent.replace('%',''));$('#overallAccuracy').textContent=`${Math.min(99,current+1)}%`;account.saveProgress({lessonId:state.lesson.id,levelId:state.level.id,accuracy:state.score,completed:true}).catch(()=>{});}}
function renderSongs(){$('#songGrid').innerHTML=songs.map(song=>`<article class="song-card"><div class="song-art" style="--tone:${song.tone}">${song.icon}</div><h3>${song.title}</h3><p>${song.artist} · ${song.duration} · ${song.sections.length} бөлім</p><button data-song="${song.id}">Әнді үйрену →</button></article>`).join('');$$('[data-song]').forEach(button=>button.onclick=()=>openSong(button.dataset.song));}
function openSong(id){state.song=songs.find(song=>song.id===id);state.songSection=0;renderSongLesson();show('songLesson');}
function renderSongLesson(){const song=state.song,section=song.sections[state.songSection];$('#songLessonTitle').textContent=song.title;$('#songLessonArtist').textContent=song.artist;$('#songSourceLink').href=song.videoUrl;$('#songVideo').src=`https://www.youtube-nocookie.com/embed/${song.videoId}?rel=0`;$('#songSectionList').innerHTML=song.sections.map((item,index)=>`<button class="song-section-button ${index===state.songSection?'active':''}" data-section="${index}"><span>${String(index+1).padStart(2,'0')} / ${song.sections.length}</span>${item.title}</button>`).join('');$$('.song-section-button').forEach(button=>button.onclick=()=>{state.songSection=Number(button.dataset.section);renderSongLesson();});$('#songSectionTitle').textContent=section.title.toUpperCase();$('#songPracticeTitle').textContent=`«${song.title}» — ${section.title}`;$('#songLyrics').innerHTML=section.lines.map(line=>`<div class="song-line">${line}</div>`).join('');}
function practiceSongSection(){const song=state.song,section=song.sections[state.songSection];state.level={id:`song-${song.id}`,number:'ӘУЕН',title:song.title,description:`${section.title}: осы жолдарды ыммен орында.`,lessons:song.sections.map((item,index)=>({id:`${song.id}-${index}`,title:item.title,gesture:'🎵',prompt:`${song.title}: ${item.title}`,hint:item.lines.join(' ')}))};state.lesson=state.level.lessons[state.songSection];renderLesson();show('lesson');toast('Ән фрагментінің AI-жаттығуы ашылды.');}

$('#continueButton').onclick=resumeLearning;$('#cameraButton').onclick=()=>openLevel('alphabet');$('#homeButton').onclick=()=>show('home');$('[data-back]').onclick=()=>show('home');$('#backToSongs').onclick=()=>show('songs');$('#songCameraPractice').onclick=practiceSongSection;$$('[data-nav]').forEach(button=>button.onclick=()=>button.dataset.nav==='learn'?resumeLearning():show(button.dataset.nav));$('#startPractice').onclick=startCamera;$('#checkGesture').onclick=scoreGesture;$('#skipExercise').onclick=()=>{const next=state.level.lessons.indexOf(state.lesson)+1;if(next<state.level.lessons.length){state.lesson=state.level.lessons[next];if(curriculum.includes(state.level))savePosition();renderLesson();}else toast('Деңгей аяқталды — керемет жұмыс!');};
document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseCamera();});window.addEventListener('pagehide',releaseCamera);
renderLevels();renderSongs();mountAccount(user=>{if(user)toast(`${user.name}, оқу жолыңыз сақталады.`);});TemporalModelAdapter.load().then(realModel=>{model=realModel;toast('Уақыттық AI-модель іске қосылды.');}).catch(()=>{});
